### ISSUE TITLE
Crash after scanning - Bahasa Apps V1.7 (Built on Nov 7)

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#614]
My apps running on Samsung A50s keeps stopping after successfully scanned it.

Hamburger menu > Delivery Preparation > Scan barcode sample > Status: Ok and will be like this. When I tried the same on the patient form, the crash doesn't happen.

![WhatsApp Image 2020-11-07 at 10 56 57 AM (1)](https://user-images.githubusercontent.com/73918009/98433247-e5d6c280-20f7-11eb-8955-9fb0b47129ee.jpeg)

**Comment by vincent-karuri** [comment]
By patient form do you mean RDT form? Are you using the same barcode for both?

Seems like it crashes for sample barcodes only.

**Comment by ellyasafaa** [comment]
Sorry, I clicked the wrong button.
I have tried it on OPPO A5s Android version 8.1.0 and it has the same issue as what I got on Samsung A50s Android versing 10

**Comment by vincent-karuri** [comment]
@ellyasafaa I believe this was addressed on the latest version which is on the playstore. Just in case, could you share a high quality image of the barcode you're scanning?

Could you also confirm if you are using different barcodes for sample collection and RDT collection forms?

**Comment by shivenbhatt1** [comment]
@ellyasafaa All functionality works when tested on Samsung J727A running Android version 8.1.0 using App version v1.7.0 built on 16 Nov 2020 and Onescan version 0.9.54 (most recent release)

**Comment by ellyasafaa** [comment]
@vincent-karuri This is the barcodes that I use that I got from Shiven. Since it was sent a long time ago, I don't know whether it is outdated or not.

For the RDT
![WhatsApp Image 2020-11-18 at 7 04 18 AM](https://user-images.githubusercontent.com/73918009/99465205-702aec00-296c-11eb-8e32-e1945d334e3f.jpeg)

For the sample
![WhatsApp Image 2020-11-18 at 7 04 18 AM (1)](https://user-images.githubusercontent.com/73918009/99465227-7c16ae00-296c-11eb-9ea1-9c449cec8354.jpeg)

**Comment by ellyasafaa** [comment]
@vincent-karuri I have just tried the App version v1.7.0 built on 18 Nov 2020 and Onescan version 0.9.54 (most recent release) on Samsung A50s Android version 10, for the sample barcode, still crash. For the RDT, it ran well

**Comment by shivenbhatt1** [comment]
@ellyasafaa are you saying that the RDT barcode was captured but not the sample barcode? Or that even the RDT barcode didn't capture?

**Comment by ellyasafaa** [comment]
@shivenbhatt1 The RDT barcode was captured and there was no crash afterward. For the sample barcode, at first, it was captured and had crash afterward. The second time I tried, I was unable to click anything on the page.

**Comment by vincent-karuri** [comment]
@ellyasafaa could you please perform tests on a phone that's not on Android 10. Also, could you uninstall the current version before manually installing any new apk?

**Comment by vincent-karuri** [comment]
The sample barcode worked fine on my end.

**Comment by ellyasafaa** [comment]
@vincent-karuri Yes, sure. I have tried on OPPO A5s Android version 8.1.0 and it crashed after scanning the sample barcode in the Delivery Preparation (Persiapan Pengiriman). Will check on another phone as well and tell you the result asap

**Comment by ellyasafaa** [comment]
@vincent-karuri I have tried on Redmi S2 Android version 8.1.0, there was a crash for the sample barcode
![WhatsApp Image 2020-11-18 at 5 43 42 PM](https://user-images.githubusercontent.com/73918009/99522439-3ab3ec00-29c8-11eb-8751-2bfad21c5695.jpeg)
![WhatsApp Image 2020-11-18 at 5 36 47 PM](https://user-images.githubusercontent.com/73918009/99522466-456e8100-29c8-11eb-9667-b77a0475b3b0.jpeg)

**Comment by vincent-karuri** [comment]
@shivenbhatt1 @ellyasafaa I have tried this on `OPPO A5s Android version 8.1.0 ` and `v1.7.0-CONFIGURABLE-RDT-SID-DEBUG` and everything works as expected.

Please make sure you have the most up-to-date APK and make sure to uninstall the existing app before installing the most up-to-date APK.

**Comment by vincent-karuri** [comment]
This is fixed.
